"""add riddles and answers

Revision ID: 5a0343c5b111
Revises: d2dcc0ec4e96
Create Date: 2024-10-18 15:55:38.601246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a0343c5b111'
down_revision = 'd2dcc0ec4e96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=64), nullable=True),
    sa.Column('image', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('riddle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clue_1', sa.String(length=64), nullable=True),
    sa.Column('clue_2', sa.String(length=64), nullable=True),
    sa.Column('clue_3', sa.String(length=64), nullable=True),
    sa.Column('question', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('riddle_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('riddle_id', sa.Integer(), nullable=True),
    sa.Column('answer_id', sa.Integer(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['answer.id'], ),
    sa.ForeignKeyConstraint(['riddle_id'], ['riddle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('riddle_answer')
    op.drop_table('riddle')
    op.drop_table('answer')
    # ### end Alembic commands ###
