"""add indig text, language, and tribe to greeting model

Revision ID: d2dcc0ec4e96
Revises: d4a5acf994d5
Create Date: 2024-10-18 13:01:22.415660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2dcc0ec4e96'
down_revision = 'd4a5acf994d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('greeting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('indiginous_text', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('language', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('tribe', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('greeting', schema=None) as batch_op:
        batch_op.drop_column('tribe')
        batch_op.drop_column('language')
        batch_op.drop_column('indiginous_text')

    # ### end Alembic commands ###
