"""change greeting text to be more specific, drop unique constraint

Revision ID: d4a5acf994d5
Revises: bf293d3e5a43
Create Date: 2024-10-18 12:55:48.746164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4a5acf994d5'
down_revision = 'bf293d3e5a43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('greeting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('english_text', sa.String(length=16), nullable=True))
        batch_op.drop_column('text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('greeting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.VARCHAR(length=16), nullable=True))
        batch_op.drop_column('english_text')

    # ### end Alembic commands ###
